# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ForestryInventory' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Include Secrets.xcconfig in Pods xcconfig files
    secrets_xcconfig = File.join(__dir__, 'Secrets.xcconfig')
    if File.exist?(secrets_xcconfig)
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference&.real_path
          if xcconfig_path && File.exist?(xcconfig_path)
            xcconfig_content = File.read(xcconfig_path)
            include_line = "#include \"#{secrets_xcconfig}\""
            unless xcconfig_content.include?(include_line)
              File.open(xcconfig_path, 'a') { |f| f.puts "\n#{include_line}" }
            end
          end
        end
      end
    end
  end
end
