export const en = {
  // App
  appName: "My Forest Tracker",

  // General
  cancel: "Cancel",
  save: "Save",
  delete: "Delete",
  close: "Close",
  edit: "Edit",
  add: "Add",
  success: "Success",
  error: "Error",

  // Header
  online: "Online",
  offline: "Offline",
  gpsActive: "GPS",

  // Tool Panel
  tools: "Tools",
  gpsTracking: "GPS Tracking",
  satelliteView: "Satellite View",
  addPoint: "Add Point",
  drawArea: "Draw Area",
  completeArea: "Complete Area",
  clearDrawing: "Clear Drawing",
  itemsList: "Items List",
  about: "About",
  language: "Language",

  // Sidebar
  inventory: "Inventory",
  noItems: "No items yet",
  export: "Export",
  import: "Import",
  items: "items",

  // Item Modal
  newPoint: "New Point",
  newArea: "New Area",
  editItem: "Edit Item",
  viewItem: "View Item",
  name: "Name",
  notes: "Notes",
  title: "Title",
  description: "Description",
  body: "Body",
  namePlaceholder: "Enter name...",
  notesPlaceholder: "Enter notes...",
  parentPlaceId: "Parent place",
  created: "Created",
  area: "Area",
  color: "Color",
  attributes: "Attributes",
  selectOption: "Select option",
  code: "Code",
  label: "Label",
  properties: "Properties",
  media: "Media",
  photos: "Photos",
  videos: "Videos",
  history: "History",
  userJournal: "User Journal",
  addHistory: "Add History Entry",
  noHistoryEntries: "No history entries yet",
  noUserJournalEntries: "No journal entries yet",
  addMedia: "Add Media",
  takePhoto: "Take Photo",
  recordVideo: "Record Video",
  chooseFromLibrary: "Choose from Library",

  // Import/Export
  importData: "Import Data",
  chooseFormat: "Choose import format",
  geoJsonAdd: "GeoJSON (Add)",
  forestandXmlImport: "Forestand XML (Convert via API)",
  zipReplaceAll: "ZIP (Replace All)",
  importedItems: "Imported {count} items",
  addedItems: "Added {count} items",
  exportFormat: "Export Format",
  chooseExportFormat: "Choose export format",
  all: "All",
  allFormats: "All formats",
  jsonOnly: "JSON only",
  csvOnly: "CSV only",
  geoJsonOnly: "GeoJSON only",
  itemsCount: "Items ({count})",
  mapProperties: "Map Properties",
  selectNameProperty: "Select property for item name",
  selectNotesProperty: "Select property for item notes",
  selectXmlFile: "Please select a .xml file",
  forestandResponseInvalid: "Failed to parse API response as GeoJSON",

  // Alerts
  deleteItem: "Delete Item",
  deleteConfirm: "Are you sure?",
  importError: "Import Error",
  exportError: "Export Error",
  exportFailed: "Failed to export data: {message}",
  importFailed: "Failed to import data: {message}",
  noDataJson: "No data.json found in the ZIP file",
  noValidFeatures: "No valid Point or Polygon features found in GeoJSON",
  invalidGeoJson: "Invalid GeoJSON: no features array found",
  parseGeoJsonFailed: "Failed to parse GeoJSON: {message}",
  forestandConvertFailed: "Failed to convert Forestand XML: {details}",
  areaMinPoints: "An area needs at least 3 points",
  nameRequired: "Please enter a name",

  // About
  aboutTitle: "My Forest Tracker",
  version: "Version",
  aboutDescription:
    "A mobile app for managing forestry inventory with GPS-based point and area mapping, media capture, and data export capabilities.",
  features: "Features",
  featureGps: "GPS point and polygon area tracking",
  featureMedia: "Photo and video attachments",
  featureHistory: "History tracking for items",
  featureExport: "Export to GeoJSON, CSV, ZIP",
  featureImport: "Import from GeoJSON",
  githubRepo: "GitHub Repository",

  // Map
  confirmLocation: "Confirm",
  addAreaPoint: "Add Point",
  setNewPosition: "Set New Position",
  completeReposition: "Done",
  cancelReposition: "Cancel",

  // Language names
  english: "English",
  swedish: "Swedish",

  // Attribute names
  ASIO: "ASIO",
  BearingCapacity: "Bearing Capacity",
  Climate: "Climate",
  DegeneratedLand: "Degenerated Land",
  Ditching: "Ditching",
  EarlierLandUse: "Earlier Land Use",
  FrostExposure: "Frost Exposure",
  GroundLayer: "Ground Layer",
  LandUseSVL: "Land Use (SVL)",
  LandUseTrad: "Land Use (Traditional)",
  LateralSoilWater: "Lateral Soil Water",
  ManagementClass: "Management Class",
  MaturityClass: "Maturity Class",
  ParticleFraction: "Particle Fraction",
  Slope: "Slope",
  SlopeDirection: "Slope Direction",
  Soil: "Soil",
  SoilDepth: "Soil Depth",
  SoilMoisture: "Soil Moisture",
  SoilTexture: "Soil Texture",
  species: "Site Index",
  SiteIndexSpec: "Site Index",
  speciesHeight: "Height",
  population: "Population",
  treeLayer: "Tree Layer",
  treeSpecies: "Tree Species",
  treeSpecies_ref: "Tree Species (ref)",
  objectPopulationId: "Population ID",
  areaWeightedAge: "Area-weighted Age",
  weightedDiameter: "Weighted Diameter",
  meanHeight: "Mean Height",
  standBasalArea: "Stand Basal Area",
  areaStandVolume: "Stand Volume per ha",
  areaStemNumber: "Stem Number per ha",
  speciesDistributionVolume: "Species Distribution (Volume)",
  SurfaceStructure: "Surface Structure",
  Vegetation: "Vegetation",
  WaterManagementClass: "Water Management Class",
  areaHa: "Area (ha)",

  // Add/Remove attributes
  addAttribute: "Add Attribute",
  selectAttributeToAdd: "Select attribute to add...",
  removeAttribute: "Remove attribute",
  confirmRemoveAttribute: "Remove this attribute?",
};

export type TranslationKeys = keyof typeof en;
